[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_anchor = "8hiwSSpPmZoT86FxkHKbsYoDFZ9sLDtwXLqQV2j7Fbvj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/yavuz/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
